### ISSUE TITLE
The result of `endOf()` is different in Firefox and Chrome.

### ISSUE THREAD

**Issue by mt-u** [kawanet/cdate#7]
Hello.
I encountered some strange behavior and would like to report it.

Running the code below gives different results in Firefox and Chrome.
```typescript
import { cdate } from 'cdate';

const d = new Date('1887-01-01T00:00:00+09:00');
console.log(d);
console.log(cdate(d).toDate(), cdate(d).format('YYYY-MM-DD HH:mm:ss'));
const endOfYear = cdate(d).endOf('year');
console.log(endOfYear.toDate(), endOfYear.format('YYYY-MM-DD HH:mm:ss'));
```

Firefox gives the expected result.
```
Date Sat Jan 01 1887 00:18:59 GMT+0918 (日本標準時)
Date Sat Jan 01 1887 00:18:59 GMT+0918 (日本標準時) 1887-01-01 00:18:59
Date Sat Dec 31 1887 23:59:59 GMT+0918 (日本標準時) 1887-12-31 23:59:59
```

I get strange results in Chrome.
```
Sat Jan 01 1887 00:18:59 GMT+0918 (日本標準時)
Sat Jan 01 1887 00:18:59 GMT+0918 (日本標準時) '1887-01-01 00:18:59'
Sun Jan 01 1888 00:00:58 GMT+0918 (日本標準時) '1888-01-01 00:00:58'
```

It seems to occur when dealing with dates in `1887` and earlier.

Here is my environment:

- Windows 11 22H2 64bit
- Firefox: 113.0.1
- Chrome: 113.0.5672.127
- Node.js: v18.14.2 (ubuntu:22.04 on Docker)

**Comment by kawanet** [comment]
Welcome to the strange world of tzdata!
https://www.m3tech.blog/entry/timezone-091859

The result above looks strange anyway. I'll check it later.
It may be happened by some differences between those browsers implementations.
`cdate` has it own internal cache of time difference. This also may cause the trouble at the other case.

**Comment by kawanet** [comment]
I've confirmed the reproduction of the issue at Chrome/Safari/Node.js v18 as you reported.
The following workaround would solve the problem even on those environments.

```
const cdateJ = cdate().utcOffset(9).cdateFn(); // GMT+09:00 

const d = new Date('1887-01-01T00:00:00+09:00');
console.log(d);
console.log(cdateJ(d).toDate(), cdateJ(d).format('YYYY-MM-DD HH:mm:ss'));
const endOfYear = cdateJ(d).endOf('year');
console.log(endOfYear.toDate(), endOfYear.format('YYYY-MM-DD HH:mm:ss'));
```
OR
```
const cdateJ = cdate().tz("Asia/Tokyo").cdateFn(); // JST

const d = new Date('1887-01-01T00:00:00+09:00');
console.log(d);
console.log(cdateJ(d).toDate(), cdateJ(d).format('YYYY-MM-DD HH:mm:ss'));
const endOfYear = cdateJ(d).endOf('year');
console.log(endOfYear.toDate(), endOfYear.format('YYYY-MM-DD HH:mm:ss'));
```

`cdateFn()` generates a customized version of `cdate()` method.
`cdateJ()` has the pretty same interface as the original `cdate()` has.
`cdateJ()` works with the fixed time zone `9` or `Asia/Toyo` as given.
Note that `utcOffset()` would be faster than `tz()` at most cases.

I usually use `cdateJ()` for my production usages.

----

This issue is due to differences in the local time zone behavior of browsers, by the way.
It seems I need more deeper dive into this.
Try the workaround above if allowed.

Thanks for your reporting.

**Comment by mt-u** [comment]
Thank you very much for your confirmation and the workaround.
I have verified that both workarounds are fine.
And I'm going to use utcOffset which told me it's faster.

Thank you for this cool project of yours!

___
PS: Due to historical reasons, it seems that dealing with datetime data accurately is quite complicated. I appreciate your hard work. Also, I found another strange behavior while trying the above method, so I will create a new issue.
